export const avatarFiles = [
  "beru.jpg",
  "gara.jpg",
  "igris.jpg",
  "itachi.png",
  "jinwoo.jpg",
  "jinwoo2.png",
  "kakashi.jpg",
  "kakashi2.jpg",
  "luffy1.jpg",
  "luffy2.jpg",
  "luffy3.png",
  "naruto.jpg",
  "natsu.png",
  "zoro.jpg",
  "zoro2.jpg",
];
export const unwantedHeaders = [
  // Vercel-specific headers
  'x-vercel-deployment-url',
  'x-vercel-id',
  'x-vercel-internal-bot-check',
  'x-vercel-internal-ingress-bucket',
  'x-vercel-internal-ingress-port',
  'x-vercel-ip-as-number',
  'x-vercel-ip-city',
  'x-vercel-ip-continent',
  'x-vercel-ip-country',
  'x-vercel-ip-country-region',
  'x-vercel-ip-latitude',
  'x-vercel-ip-longitude',
  'x-vercel-ip-postal-code',
  'x-vercel-ip-timezone',
  'x-vercel-ja4-digest',
  'x-vercel-oidc-token',
  'x-vercel-proxied-for',
  'x-vercel-proxy-signature',
  'x-vercel-proxy-signature-ts',
  'x-vercel-sc-basepath',
  'x-vercel-sc-headers',
  'x-vercel-sc-host',
  'host',
  "user-agent",
  "x-vercel-forwarded-for",
  // Other infrastructure headers
  'x-forwarded-for',
  'x-forwarded-host',
  'x-forwarded-port',
  'x-forwarded-proto',
  'x-matched-path',
  'x-real-ip',
  'forwarded',
  'connection',
  'content-length',
  // Add more headers as needed
];